service: smartparking
frameworkVersion: "3"
useDotenv: true

custom:
  pythonRequirements:
    usePoetry: true
    dockerizePip: true
  userPoolIssuerUrl:
    !Join [
      "",
      ["https://cognito-idp.${aws:region}.amazonaws.com/", !Ref UserPool],
    ]
  dynamoTableName: ${self:service}-${sls:stage}
  h3CellIndexName: H3CellIndex
  dynamodbTableArn: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:service}-${sls:stage}
  dynamodbAppResourcesArn: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:service}-${sls:stage}/*
  snsTopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:service}-${sls:stage}

provider:
  name: aws
  runtime: python3.9
  httpApi:
    authorizers:
      cognito:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${self:custom.userPoolIssuerUrl}
        audience:
          - !Ref UserPoolClientFlutter

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

functions:
  api:
    handler: backend/apps.api.main.handler
    events:
      - httpApi:
          path: "*"
          method: "*"
          authorizer:
            name: cognito
    environment:
      DYNAMO_TABLE: ${self:custom.dynamoTableName}
      H3_CELL_INDEX: ${self:custom.h3CellIndexName}
      SNS_TOPIC_ARN: ${self:custom.snsTopicArn}
      ENV: aws_lambda_mangum
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Query
        Resource:
          - ${self:custom.dynamodbTableArn}
          - ${self:custom.dynamodbAppResourcesArn}
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: ${self:custom.snsTopicArn}

  sns:
    handler: backend/apps.events.main.handler
    events:
      - sns:
          topicName: ${self:service}-${sls:stage}
          displayName: Smart parking domain events
    environment:
      DYNAMO_TABLE: ${self:custom.dynamoTableName}
      H3_CELL_INDEX: ${self:custom.h3CellIndexName}
      SNS_TOPIC_ARN: ${self:custom.snsTopicArn}
      ENV: aws_lambda_mangum

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${sls:stage}
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: False
        DeletionProtection: INACTIVE
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - Name: email
            Mutable: true
            Required: true
          - Name: given_name
            Mutable: true
            Required: false
          - Name: family_name
            Mutable: true
            Required: false
        UsernameAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: false
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
          EmailMessage: Your verification code is {####}
          EmailSubject: Your verification code
        AutoVerifiedAttributes:
          - email
    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: ${self:service}-${sls:stage}
        UserPoolId: !Ref UserPool
    GoogleIdentityProvider:
      Type: AWS::Cognito::UserPoolIdentityProvider
      Properties:
        AttributeMapping:
          given_name: "given_name"
          family_name: "family_name"
          email: "email"
        ProviderDetails:
          client_id: ${env:GOOGLE_CLIENT_ID}
          client_secret: ${env:GOOGLE_CLIENT_SECRET}
          authorize_scopes: "openid email profile"
        ProviderName: Google
        ProviderType: Google
        UserPoolId: !Ref UserPool
    UserPoolClientFlutter:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        AccessTokenValidity: 1
        AllowedOAuthFlows:
          - code
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - profile
          - openid
          - aws.cognito.signin.user.admin
        AuthSessionValidity: 3
        CallbackURLs:
          - myapp://
        ClientName: flutter-app
        DefaultRedirectURI: myapp://
        EnablePropagateAdditionalUserContextData: false
        EnableTokenRevocation: true
        ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
        GenerateSecret: false
        IdTokenValidity: 1
        LogoutURLs:
          - myapp://
        PreventUserExistenceErrors: ENABLED
        RefreshTokenValidity: 1
        SupportedIdentityProviders:
          - COGNITO
          - Google
        TokenValidityUnits:
          AccessToken: hours
          IdToken: hours
          RefreshToken: days
        UserPoolId: !Ref UserPool
      DependsOn:
        - GoogleIdentityProvider
    DynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoTableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: h3cell
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.h3CellIndexName}
            KeySchema:
              - AttributeName: h3cell
                KeyType: HASH
              - AttributeName: sk
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - name
                - street
                - coordinates
